site_name: Baseball Stats
site_url: https://baseball-stats.net
site_description: 'A web reference of common baseball statistics.'
copyright: '&copy; 2017 Justin Keller<br />All rights reserved.'
google_analytics:
site_author: Justin Keller
repo_name: baseball-stats.net
repo_url: https://github.com/nodesocket/baseball-stats.net
pages:
    - Home: index.md
    - Hitting:
        - 'Batting Average (AVG)': hitting/avg.md
        - 'On-Base Percentage (OBP)': hitting/obp.md
        - 'Slugging Average (SLG)': hitting/slg.md
        - 'On-Base Plus Slugging (OPS)': hitting/ops.md
        - 'Gross Production Average (GPA)': hitting/gpa.md
    - Pitching:
        - 'Earned Run Average (ERA)': pitching/era.md
        - 'Adjusted Earned Run Average (ERA+)': pitching/aera.md
        - 'Walks And Hits Per Inning Pitched (WHIP)': pitching/whip.md
        - 'Strikeout-To-Walk Ratio (K/BB)': pitching/kbb.md
        - 'Left-On-Base Percentage (LOB%)': pitching/lobp.md
        - 'Win-Loss Percentage (PCT)': pitching/pct.md
        - 'Power Finesse Ratio (PFR)': pitching/pfr.md
    - Baserunning:
        - 'Stolen Base Percentage (SB%)': baserunning/sbp.md
theme: material
site_favicon: 'images/favicon.ico'
extra:
    logo: images/baseball.svg
    palette:
        primary: 'blue'
        accent: 'red'
    extra:
    feature:
        tabs: true
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - pymdownx.arithmatex
